config/routes.rb
Rails.application.routes.draw do
 

 # Active admin auto added these two lines
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

# Deleted all of the original comments so don't get confused between their comments and my own

# We want the ability to add, edit. delete stories
  # In rails, there are 7 default actions;
  # index, show
  # new, create
  # edit, update
  # destroy

  resources :stories do

    # added in a do and an end so that comments are related to stories do the URL's will be related too
    resources :comments

    # votes are also related to stories so add them in the same way
    resources :votes

  end

  # Set up a URL for the homepage. root is the way we say homepage in Rails
  root "stories#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base

	# adding in an association between the comment and the story
	# my comment belongs to a story

	# we added the comma after story to tell it to update story when a new comment is created

	belongs_to :story, counter_cache: true


	# add validations
	validates :body, presence: true 


end

app/models/story.rb
class Story < ActiveRecord::Base

	# Add the neccessary associations for the comment system
	# my story has many comments

	has_many :comments 

	# my story has many votes
	has_many :votes


	# I want to check the data is what I expect. The model just handes the data.
	validates :title, presence: true,
		length: { minimum: 5 }

	validates :description, presence: true

	validates :link, presence: true, 
		uniqueness: { message: "has already been submitted" }


end

app/models/vote.rb
class Vote < ActiveRecord::Base

	# add an association

	belongs_to :story, counter_cache:true

	# adding in a validation to ensure that the votes on stories can't be voted for multiple times
	# we could use true but the {} allow us to use options
	validates :ip_address, uniqueness: { scope: :story_id}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		# this is the comment form

		# find the story that the new comment will be on
		# because we're in the comments controller we need to include story_ before id to make sure it knows it the story, not the comment ID
		@story = Story.find(params[:story_id])

		# make a new comment on the @story variable
		# the @ bit is creating a variable
		@comment = @story.comments.new

	end
	
	def create

		# this is actually creating the comment

		@story = Story.find(params[:story_id])
		@comment = @story.comments.new(comment_params)

		# if the comment saves correctly, go back to story page, if not, show new form again

		if @comment.save

			flash[:success] = "Your comment was added successfully!"

			redirect_to story_path(@story)

		else
		
			render "new"


		end	

	end

	def comment_params

		# whitelisted form data
		# get the comments form and only the body of the form
		params.require(:comment).permit(:body)

	end	

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

	# We want to add a list of all of the stories
	# In static websites this would be the index.html

	def index

		# I want to pass some data to our html
		# this data may change, so it variable
		# so we store the data in a ruby thing called a variable
		@username = "Chris"


		# we want to store some stories in a list
		# in ruby we call this an array
		# [] create an array or list in rails
		# @stories = ["Google","Facebook","Twitter", "LinkedIn"]
	

		# instead of hard coding like the above, we want to get the real stories from the database
		# this is how we would just show all the stories with no order
		# @stories = Story.all

		if params[:featured] =="true"
			# this is just showing articles where featured is true
			@stories = Story.where(is_featured: true). order("created_at desc")

			# find jus the featured stories

		# this is showing the stories by the votes_count column in decening order, followed by the title in ascencing order
		# @stories = Story.order("votes_count desc, title asc")
		# elsif is used when we have more than 2 options so we need to have another option

		elsif params[:sort] == "recent"
			# sort by recent (note, sort above is just the word we made up in the URL in the application.html file)
			@stories = Story.order("created_at desc")

		else
		
			# sort by top

			@stories = Story.order("votes_count desc, title asc")
		end	 

	end

	def show
		# we have to call the view page the same as the name in the controller
		# defining the sort of read more page aka the product page
		# params get extra information from forms and URLs
		@story = Story.find(params[:id])


	end	

	def new
		# this is our new story form
		# this will try and find a html.erb page in View called new

		# the below creates a new variable called story which is equal to adding a new line in the story database
		@story = Story.new

		
	end

	def create
		# this is so that when the user hits submit it populates the database

		@story = Story.new(story_params)

		# adding in a check to see if the data that has been entered passed the validation in the model
		# added the if to the save to create the check. every if has an end.
		# save to the database
		if @story.save

			# let the user know that it was successful
			flash[:success] = "You're story was added successfully"

			# I want to go back to the homepage (bit could go to a thank you page instead...)
			redirect_to root_path

		# this is what happens if the data doesn't pass validation and save to the database 
		else

			# lets show the add a story form again to see if they want to try again
			render "new"

		end

	end	



	def edit
		# this is the form to edit the story
		@story = Story.find(params[:id])
	end	


	def update
		# the missing thing is update hence I need to use the update tag
		# first find the id for the story we are talking about
		@story = Story.find(params[:id])

		# update this story based on the form data
		if @story.update(story_params)

			# let the user know it worked

			flash[:success] = "You've edited the story!"

			# go back to the individual product page
			redirect_to story_path(@story)

		# adding an else so that if they try and edit to something already taken

		else 

			render "edit'" 

		end
	end	

	def destroy

		# actually delete the story from the database, first find it
		@story = Story.find(params[:id])

		# remove from the database
		@story.destroy

		# let them know it's been deleted

		flash[:success] = "Holy Moley! You've deleted this story."

		# send them to the homepage

		redirect_to root_path
	
	end	

	# this is creating a shortcut to find the data from the form
	def story_params
		
		# find the data from the form
		# making sure it is the story form and that it only has the title, description and link
		params.require(:story).permit(:title, :description, :link)
	end	



end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	def create

		# actually creates the vote
		# find the story we are talking about. Using story id so it's the id outside of this controller, in the story controller

		@story = Story.find(params[:story_id])

		# make a new vote on this story
		@vote = @story.votes.new

		# as part of the vote, we want to prefill in the IP address of the user
		# the user shouldn't be able to fill this themselves, it should be automated
		@vote.ip_address = request.ip

		if @vote.save

			flash[:success]= "Thanks for the vote!"

		else

			# can pick any word where error is, doesn't mean anythign
			flash[:error]= "Woops! You've already voted..."

		end

			redirect_to story_path(@story)

	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/new.html.erb
<h2>Add a comment</h2>

<%= simple_form_for [@story, @comment] do |form| %>

	<%= form.input :body, label: "Your Comment" %>

	<%= form.button :submit %>

	<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Stack</title>
		<%= stylesheet_link_tag		"application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<header>
      <h1>
        <%= link_to image_tag("/assets/stack-logo.png"), root_path %>
      </h1>

      <nav>
        <%= link_to "Top", root_path %>

        <!-- we are adding a phrase to the URL when we click on it -->
        <%= link_to "Recent", root_path(sort: "recent") %>
        <%= link_to "Featured", root_path(featured: "true") %>
        <%= link_to "Submit", new_story_path %>
      </nav>

    </header>

      
    <article>

      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>
    </article>

	</body>
</html>

app/views/stories/_form.html.erb
<%= simple_form_for @story do |form| %>

	<%= form.input :title %>
	<%= form.input :description %>
	<%= form.input  :link, label: "URL" %>

	<%= form.button :submit %>

<% end %>

app/views/stories/edit.html.erb
<h2>Edit this story</h2>

<!-- Simply created a form as per the new page -->

<%= render "form" %>

app/views/stories/index.html.erb
<% @stories.each do |story| %>

	<div class="story">

		<h2><%= link_to story.title, story.link %></h2>
		<p><%= story.description%></p>

		<!-- added the brackets for pluralise so that it knows where it starts and ends -->
		<p><%= link_to pluralize(story.comments.size, "comment"), story_path(story) %></p>

		<p>

			<%= pluralize story.votes.size, "vote" %>

			<%= link_to "Upvote", story_votes_path(story), method: :post %>

		</p>

	</div>

<% end %>

<p>
	<%= link_to "Add a new story", new_story_path, class: "button" %>
</p>

app/views/stories/new.html.erb
<h2>Add a new story</h2>

<!-- This is a partial where the form is held in the partial called form.html.erb -->

<%= render "form" %>

app/views/stories/show.html.erb
<h2>
	<%= link_to @story.title, @story.link %>
</h2>

<p>
	<%= @story.description %>
</p>

<!-- Created_at is part of rails and doesn't need to be defined -->
<p>
	<%= @story.created_at %>
</p>

<div class="actions">

	<!-- Creating the voting button -->

	<%= link_to "Vote Up", story_votes_path(@story), method: :post %>

	<%= link_to "Edit", edit_story_path(@story), class: "edit" %>

	<!-- all links are GET by default so we need to use a method to change this to tell the server to delete not get -->
	<%= link_to "Delete", story_path(@story), method: :delete, 

	data: {confirm:"Are you sure?"}, class: "delete"

	 %>

</div>

<h3>

	<!-- this is looking for how many comments there are on each article -->
	<!-- we add in pluralize and comment in quotes which will then be pluralized depending on the number -->
	<%= pluralize @story.comments.size, "comment" %>

	<%= pluralize @story.votes.size, "vote" %>
</h3>	

<!-- this find the story, then the comments on that story and then looks at each of them.  -->
<!-- we then want to 'do' something to it -->
<!-- we can call that action anything but I have called it 'comment' -->
<% @story.comments.each do |comment| %>

	<div class="comment">
		<%= simple_format comment.body %>

		<p><%= time_ago_in_words comment.created_at %> ago</p>
	</div>

<% end %>

<p>
	<%= link_to "Add a comment", new_story_comment_path(@story) %>
</p>



<p><%= link_to "Back to homepage", root_path %></p>